os:
  - linux
  - osx
language: node_js
node_js:
  - '11.15'
cache: yarn
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo dpkg --add-architecture i386
      sudo apt-get update -yqq
      sudo apt-get install -yqq wine
    fi
before_script:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - make i
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux"]; then
        make linux64 win32 win64
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        make dmg
    fi
