os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '11.15'
cache: yarn
before_script:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      npm install -g windows-build-tools
    fi
  - export PATH="$HOME/.yarn/bin:$PATH"
  - make i
script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux"]; then
        make linux64
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
        make mac
    elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
        make windows
    fi
